name = "vehicle-partner-scraper"
main = "src/workers/partner-scraper.js"
compatibility_date = "2024-01-01"

# Cron triggers for scheduled scraping
[triggers]
crons = [
  "0 2 * * *",    # Daily at 2 AM UTC
  "0 14 * * *"    # Daily at 2 PM UTC (for twice-daily updates)
]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "vehicle-dealership-db"
database_id = "YOUR_D1_DATABASE_ID"

# R2 Storage for images (optional)
[[r2_buckets]]
binding = "R2"
bucket_name = "vehicle-images"

# KV namespace for caching (optional)
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"

# Environment variables
[vars]
MAX_CONCURRENT_SCRAPES = "3"
DEFAULT_SCRAPE_DELAY = "1000"
IMAGE_DOWNLOAD_ENABLED = "false"
ROBOTS_TXT_CHECK = "true"
