name = "vehicle-admin-api"
main = "src/workers/admin-api.js"
compatibility_date = "2024-01-01"
account_id = "928f2a6b07f166d57bb4b31b9100d1f4"

# Environment variables
[vars]
LAMBERT_WORKER_URL = "https://lambert-scraper.nick-damato0011527.workers.dev"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "vehicle-dealership-analytics"
database_id = "d70754b6-fec7-483a-b103-c1c78916c497"

# Custom domain route (optional)
# [[routes]]
# pattern = "harout.neurodivers.ca/api/admin/*"
# zone_name = "neurodivers.ca"
