name = "sltautos-scraper"
main = "sltautos-scraper.js"
compatibility_date = "2023-12-01"
account_id = "928f2a6b07f166d57bb4b31b9100d1f4"

[vars]
ENVIRONMENT = "production"
CLOUDFLARE_ACCOUNT_ID = "928f2a6b07f166d57bb4b31b9100d1f4"
CLOUDFLARE_IMAGES_ACCOUNT_HASH = "fxSXhaLsNKtcGJIGPzWBwA"
CF_IMAGES_TOKEN = "hxqfnYpHcT8FrQYyiRiOiOmkPtGkTuhdf6aCfYVT"

# Note: CF_IMAGES_TOKEN enables automatic image upload to Cloudflare Images
# Images will be uploaded to imagedelivery.net CDN instead of using sltautos.com URLs
