name = "lambert-scraper"
main = "lambert-scraper-enhanced.js"
compatibility_date = "2023-12-01"
account_id = "928f2a6b07f166d57bb4b31b9100d1f4"

[vars]
ENVIRONMENT = "production"
CLOUDFLARE_ACCOUNT_ID = "928f2a6b07f166d57bb4b31b9100d1f4"
CLOUDFLARE_IMAGES_ACCOUNT_HASH = "fxSXhaLsNKtcGJIGPzWBwA"

# Secrets (already configured in existing worker):
# - CLOUDFLARE_IMAGES_TOKEN
