name = "lambert-scraper"
main = "lambert-scraper-enhanced.js"
compatibility_date = "2023-12-01"
account_id = "928f2a6b07f166d57bb4b31b9100d1f4"

[[d1_databases]]
binding = "DB"
database_name = "vehicle-dealership-analytics"
database_id = "d70754b6-fec7-483a-b103-c1c78916c497"

[vars]
ENVIRONMENT = "production"
CLOUDFLARE_ACCOUNT_ID = "928f2a6b07f166d57bb4b31b9100d1f4"
CLOUDFLARE_IMAGES_ACCOUNT_HASH = "fxSXhaLsNKtcGJIGPzWBwA"
IMAGE_PROCESSOR_URL = "https://image-processor.nick-damato0011527.workers.dev"
CF_IMAGES_TOKEN = "hxqfnYpHcT8FrQYyiRiOiOmkPtGkTuhdf6aCfYVT"

# Note: CF_IMAGES_TOKEN is the Cloudflare Images API token
# This enables automatic image upload to Cloudflare Images
