name = "naniauto-scraper"
main = "naniauto-scraper.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { 
  ENVIRONMENT = "production",
  CLOUDFLARE_ACCOUNT_ID = "928f2a6b07f166d57bb4b31b9100d1f4",
  CLOUDFLARE_IMAGES_ACCOUNT_HASH = "fxSXhaLsNKtcGJIGPzWBwA"
}
